# Generated by Django 4.1.5 on 2023-02-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiadocapp', '0002_user_grad_year_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='approve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='process_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('SU', 'Submitted'), ('AP', 'Approved'), ('PR', 'Processed'), ('CO', 'Completed'), ('CL', 'Closed')], default='SU', max_length=2),
        ),
    ]
